services:
  - type: web
    name: django-weather-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn weather_api.wsgi:application"
    envVars:
      - key: WEATHER_API_KEY
        value: "50ccd95e67544842801101011252406"
      - key: DEBUG
        value: "False"
